/**
 * build-browser.js — Parat ka browser bundle (zero deps mini-bundler).
 *
 * Strategy SIMPLE: har src file ka body lo, usme:
 *   - "module.exports = X" ko "return X" bana do
 *   - require('./x.js') ko pehle se banaye __mod['x.js']() se replace karo
 * Har module ek function ban jata hai jo apna export return karta hai.
 * window.Parat = parat.js ka export.
 *
 * Run: node build-browser.js  → dist/parat.browser.js
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const OUT_DIR = path.join(__dirname, 'dist');
const OUT = path.join(OUT_DIR, 'parat.browser.js');

const files = ['cache.js', 'dedup.js', 'batch.js', 'queue.js', 'parat.js'];

function transform(name) {
  let code = fs.readFileSync(path.join(SRC, name), 'utf8');
  // 1) module.exports = X;  →  return X;
  code = code.replace(/module\.exports\s*=\s*/g, 'return ');
  // 2) const { A, B } = require('./x.js');  →  const { A, B } = __mod('x.js');
  code = code.replace(/require\('\.\/([a-z-]+\.js)'\)/g, "__mod('$1')");
  return code;
}

let out = `/* parat.browser.js — AUTO-GENERATED by build-browser.js. Mat edit karo. */
(function () {
  'use strict';
  var __cache = {};
  function __mod(name) {
    if (__cache[name]) return __cache[name];
    var def = __defs[name];
    if (!def) throw new Error('parat: module missing: ' + name);
    __cache[name] = def();
    return __cache[name];
  }
  var __defs = {
`;

for (const f of files) {
  const body = transform(f);
  out += `    '${f}': function () {\n${body}\n    },\n`;
}

out += `  };
  window.Parat = __mod('parat.js');
})();
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, out, 'utf8');
console.log('bundle written:', OUT, '(', out.length, 'bytes )');
